---
- name: install flatpaks
  flatpak:
    name: "{{ item.name }}"
    state: present
  loop:
    - {name: "zotero"}

- name: install applications
  package:
    name:
      - mpv
      - glances
      - htop