---
- name: Install the latest packages
  package:
    name:
      - timeshift
      - borgbackup
    state: latest

- name: configure fstab
  replace:
    path: /etc/fstab
    regexp: "{{ item.regex }}"
    replace: "{{ item.line }}"
    backup: yes
  loop:
    - {regex: 'subvol=@,', line: 'subvol=@,ssd,noatime,space_cache,commit=120,discard=async,'}
    - {regex: 'subvol=@home,', line: 'subvol=@home,ssd,noatime,space_cache,commit=120,discard=async,'}

