---
- name: install packages
  package:
    name:
      - neovim
      - python3-neovim
      - curl
      - git
    state: latest

- name: check that nvim directory exists
  file:
    path: "/home/{{ user }}/.local/share/nvim/site/autoload"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"

- name: download plugin manager
  get_url: 
    dest: "/home/{{ user }}/.local/share/nvim/site/autoload/plug.vim"
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    owner: "{{ user }}"
    group: "{{ user }}"

- name: download asdf
  shell: git clone https://github.com/asdf-vm/asdf.git /home/{{ user }}/.asdf --branch release-v0.9.1
  become_user: "{{ user }}"
  ignore_errors: True

- name: install asdf plugins
  shell: "asdf plugin add {{ item.lang }}"
  loop:
    - {lang: "python"}
    - {lang: "nodejs"}
  become_user: "{{ user }}"
  ignore_errors: True