---
- name: add docker-ce repo
  shell: dnf config-manager \
    --add-repo \
    https://download.docker.com/linux/fedora/docker-ce.repo

- name: install packages
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    enablerepo: docker-ce-stable
    state: latest