---
# source: https://www.ctrl.blog/entry/fedora-hibernate.html
#TODO: update sleep.conf
#TODO: update logind.conf
#TODO: fzf_bindings
#TODO: proper fstab patching

- name: Install additional coprs
  shell: "dnf copr enable -y {{ item.copr }}"
  loop:
    - {copr: "peterwu/iosevka"}

- name: Install the latest packages
  package:
    name:
      - tlp
      - powertop
      - smartmontools
      - timeshift
      - borgbackup
      - gnome-tweak-tool
      - cronie
      - fira-code-fonts
      - iosevka-term-fonts
      - fish
      - fzf
      - bat
      - fd-find
      - neovim
      - python3-neovim
      - curl
      - git
    state: latest

- name: mask rfkill
  shell: systemctl mask systemd-rfkill.socket

- name: configure tlp.conf
  ansible.builtin.lineinfile:
    path: /etc/tlp.conf
    regexp: "{{ item.regex }}"
    line: "{{ item.line }}"
  loop:
    - {regex: '^PCIE_ASPM_ON_BAT=', line: 'PCIE_ASPM_ON_BAT = powersupersave'}
    - {regex: '^START_CHARGE_THRESH_BAT0=', line: 'START_CHARGE_THRESH_BAT0=73'}
    - {regex: '^STOP_CHARGE_THRESH_BAT0=', line: 'STOP_CHARGE_THRESH_BAT0=82'}
    - {regex: '^START_CHARGE_THRESH_BAT1=', line: 'START_CHARGE_THRESH_BAT1=73'}
    - {regex: '^STOP_CHARGE_THRESH_BAT1=', line: 'STOP_CHARGE_THRESH_BAT1=82'}

- name: start tlp
  shell: tlp start

# - name: configure fstab ssd settings
#   replace:
#     path: /etc/fstab
#     regexp: "{{ item.regex }}"
#     replace: "{{ item.line }}"
#     backup: yes
#   loop:
#     - {regex: 'subvol=@,', line: 'subvol=@,ssd,noatime,space_cache,commit=120,discard=async,'}
#     - {regex: 'subvol=@home,', line: 'subvol=@home,ssd,noatime,space_cache,commit=120,discard=async,'}

- name: Make fish a default shell
  shell: "usermod -s /usr/bin/fish {{ user }}"

# - name: Configure fzf bindings
#   shell: fzf_configure_bindings --git_status=\cg --history=\cr --variables=\cv --directory=\cf --git_log=\cl
#   become_user: "{{ user }}"

- name: check that nvim directory exists
  file:
    path: "/home/{{ user }}/.local/share/nvim/site/autoload"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"

- name: download plugin manager
  get_url: 
    dest: "/home/{{ user }}/.local/share/nvim/site/autoload/plug.vim"
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    owner: "{{ user }}"
    group: "{{ user }}"

- name: download asdf
  shell: "git clone https://github.com/asdf-vm/asdf.git /home/{{ user }}/.asdf --branch release-v0.9.1 &&
  chown -R {{ user }}:{{ user }} /home/{{ user }}/.asdf"
  ignore_errors: True

- name: install asdf plugins
  shell: "asdf plugin add {{ item.lang }}"
  loop:
    - {lang: "python"}
    - {lang: "nodejs"}
  become_user: "{{ user }}"
  ignore_errors: True

- name: update sleep.conf to enable hibernation
  ansible.builtin.lineinfile:
    path: /etc/systemd/sleep.conf
    regexp: "{{ item.regex }}"
    line: "{{ item.line }}"
  loop:
    - {regex: '^#AllowSuspend=', line: 'AllowSuspend=yes'}
    - {regex: '^#AllowHibernation=', line: 'AllowHibernation=yes'}
    - {regex: '^#AllowSuspendThenHibernate=', line: 'AllowSuspendThenHibernate=yes'}
    - {regex: '^#HibernateDelaySec=', line: 'HibernateDelaySec=120min'}

- name: update logind.conf to enable hibernation
  ansible.builtin.lineinfile:
    path: /etc/systemd/logind.conf
    regexp: "{{ item.regex }}"
    line: "{{ item.line }}"
  loop:
    - {regex: '^#HandleLidSwitch=', line: 'HandleLidSwitch=suspend-then-hibernate'}
    - {regex: '^#HandleLidSwitchExternalPower=', line: 'HandleLidSwitchExternalPower=suspend'}


# switch to gpu rendering in firefox
# https://community.frame.work/t/linux-battery-life-tuning/6665