---
- name: install quickemu requirements
  shell: "snap install qemu-virgil --edge && \
  snap connect qemu-virgil:audio-record && \
  snap connect qemu-virgil:kvm && \
  snap connect qemu-virgil:raw-usb && \
  snap connect qemu-virgil:removable-media"

- name: download quickemu repo
  ansible.builtin.git:
    repo: 'https://github.com/quickemu-project/quickemu'
    dest: "/home/{{ user }}/quickemu"

- name: change ownership of quickemu folder
  ansible.builtin.file:
    path: "/home/{{ user }}/quickemu"
    state: directory
    recurse: yes
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Create a symbolic link for binaries
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
  loop:
    - {src: "/home/{{ user }}/quickemu/quickemu", dest: "/home/{{ user }}/.local/bin/quickemu"}
    - {src: "/home/{{ user }}/quickemu/quickget", dest: "/home/{{ user }}/.local/bin/quickget"}
